import "package:flutter/material.dart";
import "package:provider/provider.dart";
import "../../auth/auth_state.dart";
import "../../theme.dart";
import "../../widgets/dropcity_brand.dart";

class LoginScreen extends StatefulWidget{const LoginScreen({super.key});@override State<LoginScreen> createState()=>_LoginScreenState();}
class _LoginScreenState extends State<LoginScreen>{final email=TextEditingController(),pass=TextEditingController(); bool obscure=true,loading=false; @override void dispose(){email.dispose();pass.dispose();super.dispose();}
Future<void> login()async{setState(()=>loading=true);try { await context.read<AuthState>().signIn(email.text.trim(), pass.text); if (!mounted) return; Navigator.of(context).pushReplacementNamed("/dashboard"); } catch (_) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Login failed"))); } finally { if (mounted) setState(() => loading = false); }}
@override Widget build(BuildContext context)=>Scaffold(backgroundColor:dropCityCloudWhite,body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(24,32,24,24),children:[const Center(child:DropCityLogoMark(size:48)),const SizedBox(height:28),const Text("Welcome back",textAlign:TextAlign.center,style:TextStyle(color:dropCitySafeSlate,fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:6),const Text("Sign in to your courier account",textAlign:TextAlign.center,style:TextStyle(color:dropCitySlateGrey)),const SizedBox(height:30),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:"Email",prefixIcon:Icon(Icons.mail_outline))),const SizedBox(height:14),TextField(controller:pass,obscureText:obscure,decoration:InputDecoration(labelText:"Password",prefixIcon:const Icon(Icons.lock_outline),suffixIcon:IconButton(icon:Icon(obscure?Icons.visibility_off:Icons.visibility),onPressed:()=>setState(()=>obscure=!obscure)))),Align(alignment:Alignment.centerRight,child:TextButton(onPressed:(){},child:const Text("Forgot password?"))),const SizedBox(height:6),CourierPrimaryButton(label:"Sign In as Courier",backgroundColor:dropCitySafeSlate,loading:loading,onPressed:login,icon:Icons.login),const SizedBox(height:26),Row(mainAxisAlignment:MainAxisAlignment.center,children:[const Text("New courier?",style:TextStyle(color:dropCitySlateGrey)),TextButton(onPressed:()=>Navigator.of(context).pushReplacementNamed("/signup"),child:const Text("Join here"))]),const SizedBox(height:18),const Center(child:Row(mainAxisSize:MainAxisSize.min,children:[Text("Admin? Use the web console.",style:TextStyle(color:dropCitySlateGrey,fontSize:11,fontStyle:FontStyle.italic)),SizedBox(width:4),Icon(Icons.open_in_new,size:13,color:dropCitySlateGrey)]))])));}
