import "package:flutter/material.dart";
import "../auth/auth_state.dart";
import "../theme.dart";
import "../widgets/dropcity_brand.dart";

class CourierDashboardScreen extends StatefulWidget{const CourierDashboardScreen({super.key,required this.authState});final AuthState authState;@override State<CourierDashboardScreen> createState()=>_State();}
class _State extends State<CourierDashboardScreen>{bool loading=true;String state="OFFLINE";List<Map<String,dynamic>> assigned=[],pending=[];int completed=0;@override void initState(){super.initState();load();}
Future<void> load()async{setState(()=>loading=true);try{final a=await widget.authState.apiClient.getAssignedParcels();final p=await widget.authState.apiClient.getPendingParcels();final s=await widget.authState.apiClient.getCourierServiceState();if(!mounted)return;setState(() { assigned = a; pending = p; state = s["state"]?.toString() ?? "OFFLINE"; completed = a.where((x) => (x["status"]?.toString() ?? "").toUpperCase() == "COMPLETED").length; });}catch(_){ }finally{if(mounted)setState(()=>loading=false);}}
Future<void> toggle(bool online)async{await widget.authState.apiClient.setCourierOnline(online);await load();}
@override Widget build(BuildContext context){final online=state.toUpperCase()!="OFFLINE";return Scaffold(appBar:AppBar(title:const Row(children:[DropCityLogoMark(size:32),SizedBox(width:8),Text("DropCity")]),actions:[Padding(padding:const EdgeInsets.only(right:16),child:Row(children:[CircleAvatar(radius:5,backgroundColor:online?dropCityActiveMint:dropCitySlateGrey),const SizedBox(width:6),Text(online?"ONLINE":"OFFLINE",style:const TextStyle(fontSize:12,fontWeight:FontWeight.w800))]))]),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.fromLTRB(16,16,16,100),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:dropCitySafeSlate,borderRadius:BorderRadius.circular(22)),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(online?"ONLINE":"OFFLINE",style:TextStyle(color:online?dropCityActiveMint:dropCitySlateGrey,fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:4),const Text("Courier availability",style:TextStyle(color:Colors.white70))])),Switch(value:online,activeColor:dropCityActiveMint,onChanged:toggle)])),const SizedBox(height:16),Row(children:[_Metric(label:"Active Deliveries",value:"${assigned.length}"),const SizedBox(width:8),_Metric(label:"Completed Today",value:"$completed"),const SizedBox(width:8),const _Metric(label:"Courier Score",value:"78.4")]),const SizedBox(height:22),const Text("RECENT ACTIVITY",style:TextStyle(color:dropCitySlateGrey,fontSize:13,fontWeight:FontWeight.w900,letterSpacing:.8)),const SizedBox(height:8),if(loading)const LinearProgressIndicator(),...(assigned.isEmpty?pending:assigned).take(3).map((p)=>_Activity(parcel:p)),if(assigned.isEmpty&&pending.isEmpty&&!loading)const Padding(padding:EdgeInsets.all(28),child:Text("No recent activity yet.",textAlign:TextAlign.center,style:TextStyle(color:dropCitySlateGrey)))])));}}
class _Metric extends StatelessWidget{const _Metric({required this.label,required this.value});final String label,value;@override Widget build(BuildContext context)=>Expanded(child:Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16)),child:Column(children:[Text(value,style:const TextStyle(color:dropCityTransitTeal,fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text(label,textAlign:TextAlign.center,style:const TextStyle(color:dropCitySlateGrey,fontSize:11))])));}
class _Activity extends StatelessWidget{const _Activity({required this.parcel});final Map<String,dynamic> parcel;@override Widget build(BuildContext context){final status=parcel["status"]?.toString()??"ASSIGNED";return Card(child:ListTile(title:Text("Parcel ${parcel["id"]?.toString().substring(0,8)??"-"}"),subtitle:Text(parcel["destination"]?.toString()??"Route delivery"),trailing:Chip(label:Text(status),backgroundColor:dropCityActiveMint.withOpacity(.12),labelStyle:const TextStyle(color:dropCityActiveMint,fontSize:11,fontWeight:FontWeight.w800)))) ;}}
