import "package:flutter/material.dart";
import "../auth/auth_state.dart";
import "../theme.dart";
import "map_route_declaration_screen.dart";
import "route_details_screen.dart";

class RouteDeclarationScreen extends StatefulWidget{const RouteDeclarationScreen({super.key,required this.authState});final AuthState authState;@override State<RouteDeclarationScreen> createState()=>_State();}
class _State extends State<RouteDeclarationScreen>{bool loading=true;List<Map<String,dynamic>> routes=[];String filter="All";@override void initState(){super.initState();load();}Future<void> load()async{setState(()=>loading=true);try{final r=await widget.authState.apiClient.getCourierRoutes();if(mounted)setState(()=>routes=r);}finally{if(mounted)setState(()=>loading=false);}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text("My Route Templates"),actions:[Padding(padding:const EdgeInsets.only(right:12),child:FloatingActionButton.small(heroTag:"addRoute",backgroundColor:dropCityTransitTeal,onPressed:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>MapRouteDeclarationScreen(authState:widget.authState))),child:const Icon(Icons.add,color:Colors.white))) ]),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.fromLTRB(16,12,16,100),children:[Wrap(spacing:8,children:["All","Active","Completed"].map((f)=>ChoiceChip(label:Text(f),selected:filter==f,onSelected:(_)=>setState(()=>filter=f),selectedColor:dropCityTransitTeal.withOpacity(.14))).toList()),const SizedBox(height:14),if(loading)const LinearProgressIndicator(),if(routes.isEmpty&&!loading)_Empty(onAdd:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>MapRouteDeclarationScreen(authState:widget.authState)))),...routes.map((r)=>_RouteCard(route:r,onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>RouteDetailsScreen(route:r,authState:widget.authState)))))])));}
class _Empty extends StatelessWidget{const _Empty({required this.onAdd});final VoidCallback onAdd;@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(top:80),child:Column(children:[const Icon(Icons.route,size:72,color:dropCitySlateGrey),const SizedBox(height:14),const Text("No routes yet",style:TextStyle(color:dropCitySafeSlate,fontSize:20,fontWeight:FontWeight.w900)),const Text("Declare your first commute route",style:TextStyle(color:dropCitySlateGrey)),const SizedBox(height:18),ElevatedButton(onPressed:onAdd,child:const Text("Add Route"))]));}
class _RouteCard extends StatelessWidget{const _RouteCard({required this.route,required this.onTap});final Map<String,dynamic> route;final VoidCallback onTap;@override Widget build(BuildContext context)=>Card(child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(12),child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(route["name"]?.toString()??"CBD ? UZ Campus",style:const TextStyle(color:dropCitySafeSlate,fontWeight:FontWeight.w900)),const SizedBox(height:10),Wrap(spacing:8,runSpacing:8,children:[Chip(label:Text(route["start_location"]?.toString()??"Start")),Chip(label:Text(route["end_location"]?.toString()??"End")),const Chip(label:Text("ETA 35m")),Chip(label:const Text("REUSABLE"),backgroundColor:dropCityActiveMint.withOpacity(.12),labelStyle:const TextStyle(color:dropCityActiveMint,fontWeight:FontWeight.w800))])]))));}
